source-file ~/dotfiles/tmux/common.conf

# プレフィックス
set -g prefix C-a
unbind C-b

# ステータスライン
setw -g status-style fg=colour255,bg=colour234
set -g status-right-length 120
set -g status-right "\
#{?client_prefix,#[fg=colour196 bold],#[fg=colour39]}PREFIX#[default]: Ctrl+a | \
#[fg=colour82]WIN#[default]: c(new) &(kill) | \
#[fg=colour220]PANE#[default]: >(menu) x(kill) | \
#[fg=colour220]HELP#[default]: prefix+h | \
Mouse: #{?mouse,on,off} | %Y-%m-%d %H:%M \
"

# プラグイン
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'Ataraxy-Labs/opensessions'
set -g @plugin 'hiroppy/tmux-agent-sidebar'

run '~/.tmux/plugins/tpm/tpm'
